/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:randomSquareButton:794874:
  state = 1;
} //_CODE_:randomSquareButton:794874:

public void drawLoop(GButton source, GEvent event) { //_CODE_:drawLoopButton:679210:
  state = 2;
} //_CODE_:drawLoopButton:679210:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:544885:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button3:544885:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:759534:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button4:759534:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:602043:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button5:602043:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  randomSquareButton = new GButton(this, 30, 30, 80, 30);
  randomSquareButton.setText("RandomSquares");
  randomSquareButton.addEventHandler(this, "button1_click1");
  drawLoopButton = new GButton(this, 120, 30, 80, 30);
  drawLoopButton.setText("Draw Loops");
  drawLoopButton.addEventHandler(this, "drawLoop");
  button3 = new GButton(this, 1200, 660, 80, 30);
  button3.setText("New");
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 10, 640, 110, 50);
  button4.setText("Save");
  button4.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  button4.addEventHandler(this, "button4_click1");
  button5 = new GButton(this, 130, 640, 120, 50);
  button5.setText("Load");
  button5.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button5.addEventHandler(this, "button5_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton randomSquareButton; 
GButton drawLoopButton; 
GButton button3; 
GButton button4; 
GButton button5; 
