/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void randomSquare_click1(GButton source, GEvent event) { //_CODE_:randomSquareButton:794874:
  state = 1;
} //_CODE_:randomSquareButton:794874:

public void drawLoop(GButton source, GEvent event) { //_CODE_:drawLoopButton:679210:
  state = 2;
} //_CODE_:drawLoopButton:679210:

public void newButton_click1(GButton source, GEvent event) { //_CODE_:newButton:544885:
  //New button
  resetCanvas();
} //_CODE_:newButton:544885:

public void saveButton_event(GButton source, GEvent event) { //_CODE_:saveButton:759534:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:saveButton:759534:

public void loadButton_click1(GButton source, GEvent event) { //_CODE_:loadButton:602043:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:loadButton:602043:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  randomSquareButton = new GButton(this, 30, 30, 80, 30);
  randomSquareButton.setText("RandomSquares");
  randomSquareButton.addEventHandler(this, "randomSquare_click1");
  drawLoopButton = new GButton(this, 120, 30, 80, 30);
  drawLoopButton.setText("Draw Loops");
  drawLoopButton.addEventHandler(this, "drawLoop");
  newButton = new GButton(this, 1200, 660, 80, 30);
  newButton.setText("New");
  newButton.addEventHandler(this, "newButton_click1");
  saveButton = new GButton(this, 10, 640, 110, 50);
  saveButton.setText("Save");
  saveButton.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  saveButton.addEventHandler(this, "saveButton_event");
  loadButton = new GButton(this, 130, 640, 120, 50);
  loadButton.setText("Load");
  loadButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  loadButton.addEventHandler(this, "loadButton_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton randomSquareButton; 
GButton drawLoopButton; 
GButton newButton; 
GButton saveButton; 
GButton loadButton; 

